version: '3'
services:
  shopping-cart:
    build: .
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      GRAPHITE_REPORTER__HOSTNAME: graphite
      GRAPHITE_REPORTER__PORT: 2003
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - 80:80
  grafana:
    image: grafana/grafana
    environment:
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_BASIC_ENABLED: 'false'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
